### ISSUE TITLE
list of dependancies

### ISSUE THREAD

**Issue by mforde84** [KeinanLab/xwas-3.0#1]
Hi, 

Is there a dependency list for this software?

M

**Comment by LaurenLo** [comment]
The XWAS package has several components, each of which has a number of dependencies. Please see the list below (dependencies that are included in the package are noted as such):

Genotype calling:
- Java 1.5+
- Python 2.5.2+
- R 2.4+
- Python library numpy
- R library mclust

Quality control:
- smartpca (binary included)
- Perl

Imputation:
- Perl
- impute2 (binary included)

SNP association testing:
- xwas binary (included)

Gene association testing:
- xwas binary (included)
- R
- R libraries corpcor and mvtnorm

Gene-gene interaction testing:
- xwas binary (included)
- R
- R libraries corpcor and mvtnorm

Visualization:
- R
- R libraries ggplot2, optparse, and qqman
